// This file is auto-generated by scripts/generate-blog-manifest.mjs
// Do not edit manually.

export const blogModuleLoaders = {
  "from-burning-cash-to-data-driven-conversion": {
    "en": () => import("../app/[locale]/(marketing)/blog/from-burning-cash-to-data-driven-conversion/en.mdx"),
    "zh": () => import("../app/[locale]/(marketing)/blog/from-burning-cash-to-data-driven-conversion/zh.mdx"),
  },
} as const;
